FROM ruby:2.4.2
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN git clone https://github.com/dus/railsapp.git /myapp
WORKDIR /myapp
RUN gem install bundler
RUN bundle install --without development test
RUN RAILS_ENV=production rails assets:precompile
