version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    #command: rails new . --force --database=postgresql
    volumes:
      - ./theapp/:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    #if files on host are created as root, please change ownership directly on host (this happens on linux, not on mac, so letting as is for the moment)
